name: Streamlit App CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # 테스트는 향후 추가 예정
    # - name: Test with pytest
    #   run: |
    #     pytest

  # 실제 배포는 Streamlit Cloud에서 자동으로 수행되므로 수동 설정 필요
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'
  #   
  #   steps:
  #   - uses: actions/checkout@v2
  #   
  #   - name: Deploy to Streamlit Cloud
  #     run: |
  #       echo "Streamlit Cloud automatically deploys from GitHub repository" 